### ISSUE TITLE
Accept docs references with .md extension

### ISSUE THREAD

**Issue by stevenwaslander** [chutsu/ditto#18]
Seems like an easy input cleanup to let people write .md at the end of filenames when they reference them, instead of a common error causing frustration.

**Comment by chutsu** [comment]
It is actually a conscience design decision because:

- if we used a `.md` for urls in markdown it shows up in the URL as `http://yoursite.com/#docs/some_random_doc.md` while  permissible it is actually not future proof. Had we decide to use something other than markdown (e.g. reStructuredText, or ascii docs) all mention of any links have to be updated, thus creating a potentially chaotic nightmere

- it is commonly accepted in the web community see this [StackOverflow Question](http://stackoverflow.com/questions/3631153/how-come-some-site-urls-do-not-include-a-file-extension)

**Comment by stevenwaslander** [comment]
Darn, and here I thought I was being helpful.

**Comment by chutsu** [comment]
Haha, no worries if someone asks this question again I can just reference this issue.
