### ISSUE TITLE
Highlight JS

### ISSUE THREAD

**Issue by Orcomp** [chutsu/ditto#9]
Tried getting Highlight JS to work with some code blocks without success. Are there any tips to get it highlighting working with ditto?

**Comment by chutsu** [comment]
I didn't actually think people were really using it, I removed it recently I could add it back in if you want?

**Comment by Orcomp** [comment]
Yes please. Or make it optional. This would be very useful for me. Thanks

**Comment by ConnorAtherton** [comment]
@chutsu We should use bower to include external dependencies like marked and highlightjs. That would make this process super quick.

**Comment by chutsu** [comment]
@ConnorAtherton How would that work? Can I do a dynamic include in the HTML file? Not seeing how a package manager could help solve this problem. 

We would ideally want to make this project free from using as much tools as possible, because requiring the user to install `npm` and then `bower` would lose `ditto`'s light weight appeal. For now if it is a matter of including `Highlight.js` or not, we could just write a simple shell script to delete the line.

What do you think?

**Comment by chutsu** [comment]
I had another thought, if the usage of bower is purely for development purposes I'm open to it. But I would like to hide that from a end-user point view.

**Comment by ConnorAtherton** [comment]
The user wouldn't have to install anything. It would all be minified and concatenated into a file that they drop into their page and *it just works* :tm:. 

We would use bower just to keep track of what files are included in the project instead of having hardcoded copied versions. You could even take it even further and generate 2 versions; one with external plugins and one without.

**Comment by chutsu** [comment]
Ok, lets go for it then :)

**Comment by chutsu** [comment]
@Orcomp, hi just wanted you to know that I have added code highlighting back. If you want to enable it please use the latest version or version 0.12. You can turn on code highlighting in the `index.html` file, via:

    ditto.highlight_code = true;

Thanks, let me know if you found any more issues.

**Comment by Orcomp** [comment]
Thanks it works great but I had to make a change to the index.html file:

Before:

```
<!-- DITTO -->
<link rel="stylesheet" href="//chutsu.github.io/ditto/ver/latest/ditto.css">
<script src="js/ditto.js"></script>
```

After

```
<!-- DITTO -->
<link rel="stylesheet" href="//chutsu.github.io/ditto/ver/latest/ditto.css">
<script src="//chutsu.github.io/ditto/ver/latest/ditto.js"></script>
```

**Comment by chutsu** [comment]
That was intentional, I think you might have grabbed the wrong `index.html`. The `index.html` at the root of the repo is only for development purposes, I was assuming the user would use the install script described in the `README.md`. :)
